In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/processed/1_merge/step5_merge.csv", low_memory=False)
df["BIRTH_YMD"]  = pd.to_datetime(df["BIRTH_YMD"], errors="coerce")
df["ABATT_DATE"] = pd.to_datetime(df["ABATT_DATE"], errors="coerce")
df["JUDGE_DATE"] = pd.to_datetime(df["JUDGE_DATE"], errors="coerce")

print(f"로드 완료: {df.shape}")
print(f"\ntrain 출처 컬럼:")
print(df[["sido","sigungu","eupmyeondong","stn","ABATT_DATE","JUDGE_DATE",
          "JUDGE_SEX","WEIGHT","BACKFAT","REA","WINDEX","WGRADE","INSFAT",
          "YUKSAK","FATSAK","TISSUE","GROWTH","COST_AMT","AGE","BIRTH_YMD",
          "CATTLE_NO","FARM_UNIQUE_NO","LAST_GRADE"]].dtypes)

로드 완료: (2408699, 44)

train 출처 컬럼:
sido                         str
sigungu                      str
eupmyeondong                 str
stn                        int64
ABATT_DATE        datetime64[us]
JUDGE_DATE        datetime64[us]
JUDGE_SEX                    str
WEIGHT                     int64
BACKFAT                  float64
REA                      float64
WINDEX                   float64
WGRADE                       str
INSFAT                   float64
YUKSAK                   float64
FATSAK                   float64
TISSUE                   float64
GROWTH                   float64
COST_AMT                 float64
AGE                        int64
BIRTH_YMD         datetime64[us]
CATTLE_NO                    str
FARM_UNIQUE_NO               str
LAST_GRADE                   str
dtype: object


In [20]:
# sido 기본 현황
print("=== sido ===")
print(f"고유값 수: {df['sido'].nunique()}")
print(f"결측 수: {df['sido'].isnull().sum():,}")
print(f"\n분포:")
print(df['sido'].value_counts())

=== sido ===
고유값 수: 17
결측 수: 0

분포:
sido
경상북도       605621
전라남도       409421
전북특별자치도    295666
충청남도       289493
경기도        214181
경상남도       203066
강원특별자치도    153026
충청북도       138979
울산광역시       20519
제주특별자치도     19448
대구광역시       18811
세종특별자치시     18094
인천광역시       15284
대전광역시        3657
광주광역시        3208
부산광역시         181
서울특별시          44
Name: count, dtype: int64


In [21]:
# sigungu, eupmyeondong, stn 한번에 확인
for col in ["sigungu", "eupmyeondong", "stn"]:
    print(f"\n=== {col} ===")
    print(f"고유값 수: {df[col].nunique()}")
    print(f"결측 수: {df[col].isnull().sum():,}")
    print(f"상위 10개:\n{df[col].value_counts().head(10)}")


=== sigungu ===
고유값 수: 184
결측 수: 0
상위 10개:
sigungu
안동시    75667
상주시    73186
정읍시    65896
안성시    65170
영주시    53897
장흥군    49807
경주시    47525
구미시    47517
나주시    46536
홍성군    42994
Name: count, dtype: int64

=== eupmyeondong ===
고유값 수: 1306
결측 수: 0
상위 10개:
eupmyeondong
북이면    22602
남면     19064
화산면    18868
공성면    18602
서후면    18488
대덕읍    17324
해평면    17112
북후면    17094
천북면    15739
한림면    14961
Name: count, dtype: int64

=== stn ===
고유값 수: 418
결측 수: 0
상위 10개:
stn
136    63722
761    46484
837    46292
777    40025
137    37636
177    34429
925    33348
691    33305
840    31891
734    31393
Name: count, dtype: int64


In [22]:
for col in ["ABATT_DATE", "JUDGE_DATE"]:
    print(f"\n=== {col} ===")
    print(f"결측 수: {df[col].isnull().sum():,}")
    print(f"범위: {df[col].min()} ~ {df[col].max()}")
    print(f"연도 분포:\n{df[col].dt.year.value_counts().sort_index()}")


=== ABATT_DATE ===
결측 수: 0
범위: 2023-01-01 00:00:00 ~ 2025-12-30 00:00:00
연도 분포:
ABATT_DATE
2023    781368
2024    835792
2025    791539
Name: count, dtype: int64

=== JUDGE_DATE ===
결측 수: 0
범위: 2023-01-02 00:00:00 ~ 2025-12-31 00:00:00
연도 분포:
JUDGE_DATE
2023    780667
2024    831555
2025    796477
Name: count, dtype: int64


In [23]:
print("=== JUDGE_SEX ===")
print(f"고유값 수: {df['JUDGE_SEX'].nunique()}")
print(f"결측 수: {df['JUDGE_SEX'].isnull().sum():,}")
print(f"\n분포:\n{df['JUDGE_SEX'].value_counts()}")

=== JUDGE_SEX ===
고유값 수: 3
결측 수: 0

분포:
JUDGE_SEX
거세    1222465
암     1174414
수       11820
Name: count, dtype: int64


In [24]:
print("=== WEIGHT ===")
print(f"결측 수: {df['WEIGHT'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['WEIGHT'].describe())
print(f"\n하위 10개:")
print(df['WEIGHT'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['WEIGHT'].nlargest(10).values)

=== WEIGHT ===
결측 수: 0

기술통계:
count    2.408699e+06
mean     4.227503e+02
std      7.984337e+01
min      3.000000e+00
25%      3.670000e+02
50%      4.230000e+02
75%      4.790000e+02
max      8.810000e+02
Name: WEIGHT, dtype: float64

하위 10개:
[ 3 32 32 34 35 37 38 39 40 43]

상위 10개:
[881 873 872 869 862 854 848 840 837 835]


In [25]:
print(df[df['WEIGHT'] <= 10][['WEIGHT', 'AGE', 'JUDGE_SEX', 'LAST_GRADE', 'CATTLE_NO']])

         WEIGHT  AGE JUDGE_SEX LAST_GRADE  \
2126855       3    1         암         등외   

                                            CATTLE_NO  
2126855  uq66v3ASrWzlL1wEL/xLejQbkjfMp6qByLYkfueWz5c=  


In [26]:
print("=== BACKFAT ===")
print(f"결측 수: {df['BACKFAT'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['BACKFAT'].describe())
print(f"\n하위 10개:")
print(df['BACKFAT'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['BACKFAT'].nlargest(10).values)

=== BACKFAT ===
결측 수: 4,567

기술통계:
count    2.404132e+06
mean     1.263125e+01
std      5.453570e+00
min      1.000000e+00
25%      9.000000e+00
50%      1.200000e+01
75%      1.500000e+01
max      9.800000e+01
Name: BACKFAT, dtype: float64

하위 10개:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

상위 10개:
[98. 90. 89. 87. 82. 79. 78. 76. 75. 75.]


In [27]:
# 상위값 확인
print("BACKFAT 50 이상 분포:")
print(f"행 수: {(df['BACKFAT'] >= 50).sum():,}")
print(df[df['BACKFAT'] >= 50][['BACKFAT', 'AGE', 'JUDGE_SEX', 'LAST_GRADE', 'WEIGHT']].sort_values('BACKFAT', ascending=False).head(20))

BACKFAT 50 이상 분포:
행 수: 448
         BACKFAT  AGE JUDGE_SEX LAST_GRADE  WEIGHT
660626      98.0   35         암         1C     357
58754       90.0   91         암         3C     399
138534      89.0   56         암        1+C     374
515641      87.0   57         암         3C     339
477028      82.0  112         암         3C     412
150285      79.0   83         암         1C     465
1108851     78.0  159         암         3C     403
137595      76.0   41         암       1++C     361
962787      75.0  138         암         3C     391
2204184     75.0   79         암         2C     454
146059      73.0  186         암         3C     493
2210862     71.0  113         암         3C     481
1530849     71.0   71         암         2C     426
1215111     71.0  177         암         3C     473
1971038     70.0  126         암         1C     518
1822455     70.0  132         암         2C     408
491277      70.0   87         암        1+C     376
1917001     70.0  156         암         3C     403
2253

In [28]:
print("=== REA ===")
print(f"결측 수: {df['REA'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['REA'].describe())
print(f"\n하위 10개:")
print(df['REA'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['REA'].nlargest(10).values)

=== REA ===
결측 수: 5,188

기술통계:
count    2.403511e+06
mean     9.312451e+01
std      1.506140e+01
min      1.000000e+00
25%      8.400000e+01
50%      9.300000e+01
75%      1.030000e+02
max      1.960000e+02
Name: REA, dtype: float64

하위 10개:
[1. 2. 2. 2. 2. 3. 3. 3. 3. 3.]

상위 10개:
[196. 195. 195. 192. 190. 190. 189. 189. 188. 187.]


In [29]:
print("REA 10 이하 분포:")
print(f"행 수: {(df['REA'] <= 10).sum():,}")
print(df[df['REA'] <= 10][['REA', 'BACKFAT', 'WEIGHT', 'WINDEX', 'AGE', 'JUDGE_SEX', 'LAST_GRADE']].sort_values('REA'))

REA 10 이하 분포:
행 수: 28
          REA  BACKFAT  WEIGHT  WINDEX  AGE JUDGE_SEX LAST_GRADE
2044772   1.0      1.0     212   57.91   29         암         3C
23994     2.0      NaN     109     NaN    8         암         등외
604112    2.0     22.0     543   53.85   30        거세       1++C
573555    2.0     22.0     475   53.43   30        거세        1+C
177623    2.0      1.0     151   59.31   32         암         등외
252676    3.0     18.0     379   52.53   54         암         1C
722749    3.0     18.0     476   54.55   32        거세         1C
308598    3.0     13.0     449   55.81   30        거세       1++C
1807664   3.0      NaN     129     NaN   19         수         등외
596259    3.0      NaN     180     NaN   53         암         등외
660626    3.0     98.0     357   31.22   35         암         1C
1283451   4.0      NaN     155     NaN   19         암         등외
884287    4.0      1.0     179   58.99  130         암         등외
564072    4.0      NaN     148     NaN   26         암         등외
347

In [30]:
print("=== WINDEX ===")
print(f"결측 수: {df['WINDEX'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['WINDEX'].describe())
print(f"\n하위 10개:")
print(df['WINDEX'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['WINDEX'].nlargest(10).values)

=== WINDEX ===
결측 수: 5,252

기술통계:
count    2.403447e+06
mean     6.151405e+01
std      1.824431e+00
min      2.919000e+01
25%      6.040000e+01
50%      6.158000e+01
75%      6.263000e+01
max      7.732000e+01
Name: WINDEX, dtype: float64

하위 10개:
[29.19 31.22 35.16 38.73 39.59 39.98 41.31 42.62 42.69 44.98]

상위 10개:
[77.32 74.77 74.68 74.49 74.43 74.24 74.2  74.15 74.15 73.87]


In [31]:
print("=== WGRADE ===")
print(f"결측 수: {df['WGRADE'].isnull().sum():,}")
print(f"\n분포:")
print(df['WGRADE'].value_counts())

=== WGRADE ===
결측 수: 0

분포:
WGRADE
B        1146958
A         799635
C         456854
-99.0       4814
D            438
Name: count, dtype: int64


In [32]:
df['WGRADE'] = df['WGRADE'].replace('-99.0', np.nan)
df['WGRADE'] = df['WGRADE'].replace(-99.0, np.nan)

print(f"처리 후 WGRADE 결측 수: {df['WGRADE'].isnull().sum():,}")
print(f"\n분포:")
print(df['WGRADE'].value_counts())

처리 후 WGRADE 결측 수: 4,814

분포:
WGRADE
B    1146958
A     799635
C     456854
D        438
Name: count, dtype: int64


In [33]:
for col in ["INSFAT", "YUKSAK", "FATSAK", "TISSUE", "GROWTH"]:
    print(f"\n=== {col} ===")
    print(f"결측 수: {df[col].isnull().sum():,}")
    print(df[col].describe())


=== INSFAT ===
결측 수: 5,331
count    2.403368e+06
mean     5.423036e+00
std      2.199511e+00
min      1.000000e+00
25%      4.000000e+00
50%      6.000000e+00
75%      7.000000e+00
max      9.000000e+00
Name: INSFAT, dtype: float64

=== YUKSAK ===
결측 수: 5,269
count    2.403430e+06
mean     4.967826e+00
std      4.916512e-01
min      1.000000e+00
25%      5.000000e+00
50%      5.000000e+00
75%      5.000000e+00
max      8.000000e+00
Name: YUKSAK, dtype: float64

=== FATSAK ===
결측 수: 4,743
count    2.403956e+06
mean     3.067800e+00
std      3.704607e-01
min      1.000000e+00
25%      3.000000e+00
50%      3.000000e+00
75%      3.000000e+00
max      8.000000e+00
Name: FATSAK, dtype: float64

=== TISSUE ===
결측 수: 5,320
count    2.403379e+06
mean     2.183306e+00
std      1.061440e+00
min      1.000000e+00
25%      1.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      5.000000e+00
Name: TISSUE, dtype: float64

=== GROWTH ===
결측 수: 9
count    2.408690e+06
mean     4.176861e+00


In [34]:
print(df[df['GROWTH'].isnull()]['LAST_GRADE'].value_counts())

LAST_GRADE
등외    9
Name: count, dtype: int64


In [35]:
print("=== COST_AMT ===")
print(f"결측 수: {df['COST_AMT'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['COST_AMT'].describe())
print(f"\n하위 10개:")
print(df['COST_AMT'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['COST_AMT'].nlargest(10).values)

=== COST_AMT ===
결측 수: 885,003

기술통계:
count    1.523696e+06
mean     1.666181e+04
std      4.212825e+03
min      0.000000e+00
25%      1.390000e+04
50%      1.694900e+04
75%      1.940000e+04
max      1.500000e+05
Name: COST_AMT, dtype: float64

하위 10개:
[  0. 100. 160. 350. 500. 500. 500. 500. 530. 600.]

상위 10개:
[150000. 140000. 119000. 110000.  88880.  80164.  80000.  77989.  72223.
  67859.]


In [36]:
# 하위값 상세 확인
print("COST_AMT 1000 이하 분포:")
print(f"행 수: {(df['COST_AMT'] <= 1000).sum():,}")
print(df[df['COST_AMT'] <= 1000][['COST_AMT', 'WEIGHT', 'AGE', 'JUDGE_SEX', 'LAST_GRADE']].sort_values('COST_AMT').head(20))

COST_AMT 1000 이하 분포:
행 수: 48
         COST_AMT  WEIGHT  AGE JUDGE_SEX LAST_GRADE
225087        0.0     405   36        거세        1+A
2126855     100.0       3    1         암         등외
21752       160.0      55    7         암         등외
641464      350.0      45   17         암         등외
387695      500.0      77   13        거세         등외
23752       500.0      64    7         수         등외
1108856     500.0     185  181         암         등외
959756      500.0      74    6         수         등외
23977       530.0      65    6         암         등외
23751       600.0      66    6         암         등외
2203235     600.0      32    6         암         등외
21438       610.0      84    8         암         등외
21678       610.0      67    7         암         등외
23978       610.0      72    8         수         등외
959607      660.0      53    6         암         등외
23975       690.0      86    7         수         등외
23573       760.0      73   10         암         등외
134994      770.0      48    7     

In [37]:
print(df[df['COST_AMT'] == 0][['COST_AMT', 'WEIGHT', 'AGE', 'JUDGE_SEX', 'LAST_GRADE', 'WGRADE', 'BACKFAT', 'REA']])

        COST_AMT  WEIGHT  AGE JUDGE_SEX LAST_GRADE WGRADE  BACKFAT   REA
225087       0.0     405   36        거세        1+A      A      5.0  77.0


In [38]:
df.loc[df['COST_AMT'] == 0, 'COST_AMT'] = np.nan

print(f"처리 후 COST_AMT 결측 수: {df['COST_AMT'].isnull().sum():,}")
print(f"처리 후 최솟값: {df['COST_AMT'].min()}")

처리 후 COST_AMT 결측 수: 885,004
처리 후 최솟값: 100.0


In [39]:
print("=== AGE ===")
print(f"결측 수: {df['AGE'].isnull().sum():,}")
print(f"\n기술통계:")
print(df['AGE'].describe())
print(f"\n하위 10개:")
print(df['AGE'].nsmallest(10).values)
print(f"\n상위 10개:")
print(df['AGE'].nlargest(10).values)

=== AGE ===
결측 수: 0

기술통계:
count    2.408699e+06
mean     4.257461e+01
std      2.186101e+01
min      1.000000e+00
25%      3.100000e+01
50%      3.300000e+01
75%      4.700000e+01
max      3.440000e+02
Name: AGE, dtype: float64

하위 10개:
[1 2 3 3 4 4 5 6 6 6]

상위 10개:
[344 338 309 293 293 289 285 285 284 283]


In [40]:
# 하위값 확인
print("AGE 6 이하:")
print(df[df['AGE'] <= 6][['AGE', 'WEIGHT', 'JUDGE_SEX', 'LAST_GRADE']].sort_values('AGE').head(10))

# 상위값 확인
print("\nAGE 200 이상:")
print(f"행 수: {(df['AGE'] >= 200).sum():,}")
print(df[df['AGE'] >= 200][['AGE', 'WEIGHT', 'JUDGE_SEX', 'LAST_GRADE']].sort_values('AGE', ascending=False).head(10))

AGE 6 이하:
         AGE  WEIGHT JUDGE_SEX LAST_GRADE
2126855    1       3         암         등외
2127020    2      47         암         등외
2125590    3      35         암         등외
1926596    3      37         암         등외
2126907    4      56         수         등외
1926597    4      45         암         등외
2201468    5      40         수         등외
23751      6      66         암         등외
1219279    6      62         암         등외
1219151    6      92         수         등외

AGE 200 이상:
행 수: 1,070
         AGE  WEIGHT JUDGE_SEX LAST_GRADE
1342182  344     233         암         3B
1340039  338     274         암         3B
2135002  309     229         암         3B
1108857  293     236         암         3C
610117   293     246         암         3B
880067   289     222         암         3B
1367182  285     210         암         3B
130513   285     220         암         3B
441547   284     295         암        1+B
1524972  283     314         암         3A


In [41]:
df.to_csv("../../data/processed/2_preprocess/step1_train.csv",
          index=False, encoding="utf-8-sig")
print(f"저장 완료: {df.shape}")

저장 완료: (2408699, 44)
